### ISSUE TITLE
Istio 1.6.8 - new rotated certs are not stored to /etc/istio-certs volumeMount

### ISSUE THREAD

**Issue by satishmane** [banzaicloud/istio-operator#500] opened 2020-08-26 11:43 UTC
Bug description

Added below annotations to pod. On sidecar injection, I can see certs stored in /etc/istio-certs volume.
exec -it -n test -c istio-proxy-- ls -ltr /etc/istio-certs
exec -it -n test -c istio-proxy-- curl http://localhost:15000/certs
exec -it -n test -c istio-proxy-- cat /etc/istio-certs/cert-chain.pem

But when certs expire and new certs are issued. the new certs are not written to istio-certs and /etc/istio-certs volume and volumeMount. I compared content of cert-chain.pem file. They are exactly same.

  annotations:
    proxy.istio.io/config: |
      proxyMetadata:
        OUTPUT_CERTS: /etc/istio-certs
        SECRET_TTL: 5m
    sidecar.istio.io/userVolume: '[{"name": "istio-certs", "emptyDir": {"medium": "Memory"}}]'
    sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-certs"}]
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Expected behavior

Everytime new istio certs are issued, they must be overwritten to /etc/istio-certs volume

Steps to reproduce the bug

Added below annotations and check certs content after every 5 minutes of expiry. First time issued certs are only seen

  annotations:
    proxy.istio.io/config: |
      proxyMetadata:
        OUTPUT_CERTS: /etc/istio-certs
        SECRET_TTL: 5m
    sidecar.istio.io/userVolume: '[{"name": "istio-certs", "emptyDir": {"medium": "Memory"}}]'
    sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-certs"}]
Version (include the output of istioctl version --remote and kubectl version and helm version if you used Helm)

How was Istio installed?
Using banzai istio operator

It works fine i.e. stores new certs to /etc/istio-certs volume if I install istio using istioctl

**Comment by waynz0r** [comment] 2020-08-26 12:42
@satishmane,

which operator and proxy image versions do you use?

**Comment by satishmane** [comment] 2020-08-26 13:16
@waynz0r 
Here is output from describe

 istio-proxy:
    Container ID:  
    Image:         docker.io/istio/proxyv2:1.6.8

   manager:
    Image:      banzaicloud/istio-operator:0.6.11

**Comment by waynz0r** [comment] 2020-08-26 19:33
@satishmane,

are you sure it works with `istioctl` based install?

I tested it with `istioctl v1.6.8` and it seems to me that there is a bug  in the upstream `docker.io/istio/proxyv2:1.6.8` image. 

The initial cert dump happens, but because of the bug the cert won't be overwritten in the output directory when the rotation happens.

**Comment by satishmane** [comment] 2020-08-27 02:32
@waynz0r 

Please find below sample httpbin app test, it has proxy version 1.6.8. I pasted pod contents. And also certs file timestamps changing every 5 minute as they get dumped.

kubectl exec -it pods/httpbin-6dbf8fd74-cplg4 -n demo -c istio-proxy -- ls -ltr /etc/istio-certs
total 12
-rwxr-xr-x 1 istio-proxy istio-proxy 1675 Aug 27 02:20 key.pem
-rwxr-xr-x 1 istio-proxy istio-proxy 2193 Aug 27 02:20 cert-chain.pem
-rwxr-xr-x 1 istio-proxy istio-proxy 1054 Aug 27 02:20 root-cert.pem
kubectl exec -it pods/httpbin-6dbf8fd74-cplg4 -n demo -c istio-proxy -- ls -ltr /etc/istio-certs
total 12
-rwxr-xr-x 1 istio-proxy istio-proxy 1054 Aug 27 02:20 root-cert.pem
-rwxr-xr-x 1 istio-proxy istio-proxy 1679 Aug 27 02:25 key.pem
-rwxr-xr-x 1 istio-proxy istio-proxy 2193 Aug 27 02:25 cert-chain.pem
s
kubectl exec -it pods/httpbin-6dbf8fd74-cplg4 -n demo -c istio-proxy -- ls -ltr /etc/istio-certs
total 12
-rwxr-xr-x 1 istio-proxy istio-proxy 1054 Aug 27 02:20 root-cert.pem
-rwxr-xr-x 1 istio-proxy istio-proxy 1679 Aug 27 02:30 key.pem
-rwxr-xr-x 1 istio-proxy istio-proxy 2189 Aug 27 02:30 cert-chain.pem


httpbin pod yamp dump
=================

apiVersion: v1
kind: Pod
metadata:
  annotations:
    proxy.istio.io/config: |
      proxyMetadata:
        OUTPUT_CERTS: /etc/istio-certs
        SECRET_TTL: 5m
    sidecar.istio.io/status: '{"version":"ed4e6e8ed4ffa03fe7d5b9d2c27cc8c478625ade64be2859cae3da0db9e5ee2e","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert","istio-certs"],"imagePullSecrets":null}'
    sidecar.istio.io/userVolume: '[{"name": "istio-certs", "emptyDir": {"medium":
      "Memory"}}]'
    sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-certs"}]'
  creationTimestamp: "2020-08-27T02:20:04Z"
  generateName: httpbin-6dbf8fd74-
  labels:
    app: httpbin
    istio.io/rev: default
    pod-template-hash: 6dbf8fd74
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: httpbin
    service.istio.io/canonical-revision: v1
    version: v1
  name: httpbin-6dbf8fd74-cplg4
  namespace: demo
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: httpbin-6dbf8fd74
    uid: 457eccd7-e78c-11ea-a87d-4201ac100406
  resourceVersion: "95535207"
  selfLink: /api/v1/namespaces/demo/pods/httpbin-6dbf8fd74-cplg4
  uid: d15c66a7-e80b-11ea-a87d-4201ac100406
spec:
  containers:
  - image: docker.io/kennethreitz/httpbin
    imagePullPolicy: IfNotPresent
    name: httpbin
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: httpbin-token-nnsx2
      readOnly: true
  - args:
    - proxy
    - sidecar
    - --domain
    - $(POD_NAMESPACE).svc.cluster.local
    - --serviceCluster
    - httpbin.$(POD_NAMESPACE)
    - --proxyLogLevel=warning
    - --proxyComponentLogLevel=misc:error
    - --trust-domain=cluster.local
    - --concurrency
    - "2"
    env:
    - name: JWT_POLICY
      value: third-party-jwt
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: CA_ADDR
      value: istiod.istio-system.svc:15012
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: CANONICAL_SERVICE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['service.istio.io/canonical-name']
    - name: CANONICAL_REVISION
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['service.istio.io/canonical-revision']
    - name: PROXY_CONFIG
      value: |
        {"proxyMetadata":{"OUTPUT_CERTS":"/etc/istio-certs","SECRET_TTL":"5m"}}
    - name: ISTIO_META_POD_PORTS
      value: |-
        [
            {"containerPort":80,"protocol":"TCP"}
        ]
    - name: ISTIO_META_APP_CONTAINERS
      value: |-
        [
            httpbin
        ]
    - name: ISTIO_META_CLUSTER_ID
      value: Kubernetes
    - name: ISTIO_META_INTERCEPTION_MODE
      value: REDIRECT
    - name: ISTIO_METAJSON_ANNOTATIONS
      value: |
        {"proxy.istio.io/config":"proxyMetadata:\n  OUTPUT_CERTS: /etc/istio-certs\n  SECRET_TTL: 5m\n","sidecar.istio.io/userVolume":"[{\"name\": \"istio-certs\", \"emptyDir\": {\"medium\": \"Memory\"}}]","sidecar.istio.io/userVolumeMount":"[{\"name\": \"istio-certs\", \"mountPath\": \"/etc/istio-certs\"}]"}
    - name: ISTIO_META_WORKLOAD_NAME
      value: httpbin
    - name: ISTIO_META_OWNER
      value: kubernetes://apis/apps/v1/namespaces/demo/deployments/httpbin
    - name: ISTIO_META_MESH_ID
      value: cluster.local
    - name: OUTPUT_CERTS
      value: /etc/istio-certs
    - name: SECRET_TTL
      value: 5m
    - name: ISTIO_KUBE_APP_PROBERS
      value: '{}'
    image: docker.io/istio/proxyv2:1.6.8
    imagePullPolicy: Always
    name: istio-proxy
    ports:
    - containerPort: 15090
      name: http-envoy-prom
      protocol: TCP
    readinessProbe:
      failureThreshold: 30
      httpGet:
        path: /healthz/ready
        port: 15021
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - ALL
      privileged: true
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/istio
      name: istiod-ca-cert
    - mountPath: /var/lib/istio/data
      name: istio-data
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /var/run/secrets/tokens
      name: istio-token
    - mountPath: /etc/istio/pod
      name: istio-podinfo
    - mountPath: /etc/istio-certs
      name: istio-certs
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: httpbin-token-nnsx2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - istio-iptables
    - -p
    - "15001"
    - -z
    - "15006"
    - -u
    - "1337"
    - -m
    - REDIRECT
    - -i
    - '*'
    - -x
    - ""
    - -b
    - '*'
    - -d
    - 15090,15021,15020
    env:
    - name: OUTPUT_CERTS
      value: /etc/istio-certs
    - name: SECRET_TTL
      value: 5m
    image: docker.io/istio/proxyv2:1.6.8
    imagePullPolicy: Always
    name: istio-init
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 10m
        memory: 10Mi
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        drop:
        - ALL
      privileged: true
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  nodeName: gke-ampauto-dev02-us-node-pool-servic-b4c41262-grp-k03m
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1337
  serviceAccount: httpbin
  serviceAccountName: httpbin
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: httpbin-token-nnsx2
    secret:
      defaultMode: 420
      secretName: httpbin-token-nnsx2
  - emptyDir:
      medium: Memory
    name: istio-envoy
  - emptyDir: {}
    name: istio-data
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: labels
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: istio-podinfo
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
  - configMap:
      defaultMode: 420
      name: istio-ca-root-cert
    name: istiod-ca-cert
  - emptyDir:
      medium: Memory
    name: istio-certs
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-08-27T02:20:06Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-08-27T02:20:09Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-08-27T02:20:09Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-08-27T02:20:04Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://6e0e0c8f7b7799db941cab96e0bedd16706e99c2b011b38f1d5a6da2f54bf14d
    image: kennethreitz/httpbin:latest
    imageID: docker-pullable://kennethreitz/httpbin@sha256:599fe5e5073102dbb0ee3dbb65f049dab44fa9fc251f6835c9990f8fb196a72b
    lastState: {}
    name: httpbin
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-08-27T02:20:06Z"
  - containerID: docker://d3f35711e42492dcb773c6e84d8290ab07037df8a66a4ced16a39163ce7b7bb5
    image: istio/proxyv2:1.6.8
    imageID: docker-pullable://istio/proxyv2@sha256:1d3a72f72814d9895cd6dbd450d6badefb353fe99f3f4a8860ec4968136c04e0
    lastState: {}
    name: istio-proxy
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-08-27T02:20:06Z"
  hostIP: 172.16.2.58
  initContainerStatuses:
  - containerID: docker://fa10fbf19ed8f10f51a654332e38a9a9e2af7dd17478c05647089d35a43296cc
    image: istio/proxyv2:1.6.8
    imageID: docker-pullable://istio/proxyv2@sha256:1d3a72f72814d9895cd6dbd450d6badefb353fe99f3f4a8860ec4968136c04e0
    lastState: {}
    name: istio-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://fa10fbf19ed8f10f51a654332e38a9a9e2af7dd17478c05647089d35a43296cc
        exitCode: 0
        finishedAt: "2020-08-27T02:20:05Z"
        reason: Completed
        startedAt: "2020-08-27T02:20:05Z"
  phase: Running
  podIP: 172.18.7.47
  qosClass: Burstable
  startTime: "2020-08-27T02:20:04Z"

**Comment by Laci21** [comment] 2021-01-05 16:30
Hi @satishmane,

As verified in [this comment](https://github.com/istio/istio/issues/26821#issuecomment-683192675), this was indeed a bug in the upstream 1.6.8 proxy image. Should be solved in 1.6.9 and in all Istio 1.7 and 1.8 versions. (Since Istio 1.6 is EOL it is recommended to update to those versions.)

Closing this as the issue is solved upstream and this is not an operator issue.

**Closed by Laci21** 2021-01-05 16:30 UTC
